theme = "onedark_local"

[editor]
true-color = true
undercurl = true
auto-completion = true
auto-info = true
cursorline = true  # 光标 行高亮
color-modes = true
idle-timeout = 40

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[icons.vcs]
enabled = true

[icons.kind]
enabled = true
number = ""
string = ""
function = "󰊕"
color = "󰌁"

[icons.fs]
enabled = true
php = { glyph = "", color = "#1976D2" }
godot = { glyph = "", color = "#2196F3" }
gd = { glyph = "", color = "#2196F3" }
