# 继承 onlight
inherits = "onelight"

"attribute" = { fg = "pink" }
"special" = { fg = "blue" }
"property" = { fg = "purple" }
"module" = { fg = "blue" }
"markup.raw.block" = { fg = "brown" }
"diff.delta.conflict" = {fg = "blue"}

# 使用 term 默认的背景色，提供 opacity 透明功能
# "ui.background" = {}

"ui.popup.info" = { fg = "blue" }

"ui.picker.header" = { fg = "purple"}
"ui.picker.header.active" = { fg = "blue"}
